name: AzureFunctions-Dev-CI-Pipeline

on: 
  push:
    branches:
      - dev
    paths:
      - '**/AzFuncs/**'
    
jobs:
  build-az-function-solution:

  #build the code
  
    runs-on: ubuntu-latest

    env:
      SolutionPath: ./src/AzFuncs/PetIdentification.sln
     
    #define steps of the job

    steps:
      
      #checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      #Setup dotnet core
      - name:  Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      # Build the code
      - name: Build the code
        run: dotnet build ${{env.SolutionPath}}
      
      # Setup directory for uploading test results
      - name: MakeDirectory For XUnit results
        run: mkdir -p TestResults

      #Run the tests
      - name: Run Xunit Tests
        run: dotnet test ${{env.SolutionPath}} --logger html --results-directory TestResults

      # Upload the test results as artifacts
      - name: Upload Test results
        uses: actions/upload-artifact@v2
        with:
          name : TestRunReports
          path: TestResults


  